Fix error: failed to open file /root/.cache/uv/sdists-v9/.git: Permission denied (ALB-164)
The Pull Request https://github.com/etalab-ia/albert-conversation/pull/98
caused the following bug when starting Docker image albert-conversation/app:

```
error: failed to open file /root/.cache/uv/sdists-v9/.git: Permission denied (os error 13)
```

Why? Because the Docker image is executed in production with parameters UID=1001 and GID=1001

This commit changes the owner of /root/.cache/* files during image build.

Reference: https://linear.app/albert-conversation/issue/ALB-164/